Endpoint 1
jeffgtxjava/Upgrad_Quora pull request #9
Opened 2020-12-05 16:37 UTC by jeffgtxjava

@saharsa @vishalint Please check and Review. 

Once Endpoint is merged you can rebase the changes and update the PR.

2020-12-05 17:07 UTC, vishalint submitted a review, later dismissed

2020-12-05 18:14 UTC, saharsa requested changes
Please have a look at the review comments. Some require changes, some are pointers that we can think about.

2020-12-05 18:14 UTC, saharsa commented on quora-api/src/main/java/com/upgrad/quora/api/controller/AdminController.java
> +    public ResponseEntity<UserDeleteResponse> deleteUserByUuid(@PathVariable("userId") String uuid, @RequestHeader(
I think it'll be better to stick to the method names mentioned in the question "userDelete". Just in case the evaluator is strict about it.

2020-12-05 18:14 UTC, saharsa commented on quora-api/src/main/java/com/upgrad/quora/api/controller/AdminController.java
> +
Formatting should be as per Google Java Style Guide

2020-12-05 18:14 UTC, saharsa commented on quora-api/src/main/java/com/upgrad/quora/api/controller/CommonController.java
> +    public ResponseEntity<UserDetailsResponse> getUserDetailByUuid(@PathVariable("userId") final String userUuid,
"userProfile" ?

2020-12-05 18:14 UTC, saharsa commented on quora-api/src/main/java/com/upgrad/quora/api/controller/UserController.java
> +        SignupUserResponse userResponse = new SignupUserResponse().id(createdUserEntity.getUuid()).status("REGISTERED");
"USER SUCCESSFULLY REGISTERED"

2020-12-05 18:14 UTC, saharsa commented on quora-api/src/main/java/com/upgrad/quora/api/controller/UserController.java
> +        userEntity.setSalt("abc1234");
Not required. Because in signupBusinessService.signup you are generating randomized salt.

2020-12-05 18:14 UTC, saharsa commented on quora-api/src/main/java/com/upgrad/quora/api/controller/UserController.java
> +        signoutResponse.setMessage("SIGNED OUT SUCCESSFULLY");
Just a thought here. I am not sure if it needs to be implemented right now or not. But the JWT token should also be invalidated i.e. its "exp" payload value should be set as logout/signout time, so that the token on client side is no longer reusable by the UI.

2020-12-05 18:14 UTC, saharsa commented on quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java
> +        }catch (NoResultException nre) {
Should we also have a more generic exception handler here as well? Because another very common Exception thrown by getSingleResult is NonUniqueResultException.

2020-12-05 18:14 UTC, saharsa commented on quora-service/src/main/java/com/upgrad/quora/service/business/UserAdminBusinessService.java
> +        if(userAuthEntity.getLogoutAt() != null) {
What if user has not logged out, but token has expired? Then also user should not be allowed access.

2020-12-05 18:14 UTC, saharsa commented on quora-service/src/main/java/com/upgrad/quora/service/business/UserAdminBusinessService.java
> +        UserAuthEntity userAuthEntity1 = userDao.getUserAuthTokenByUuid(userUuid);
Should it be userDao.getUserByUuid? Please check. Because you are checking the presence of the user here, not if user auth token is present or not.

2020-12-05 18:29 UTC, jeffgtxjava commented on quora-api/src/main/java/com/upgrad/quora/api/controller/AdminController.java
> +    public ResponseEntity<UserDeleteResponse> deleteUserByUuid(@PathVariable("userId") String uuid, @RequestHeader(
ok, I will change accordingly

2020-12-05 18:32 UTC, jeffgtxjava commented on quora-api/src/main/java/com/upgrad/quora/api/controller/CommonController.java
> +    public ResponseEntity<UserDetailsResponse> getUserDetailByUuid(@PathVariable("userId") final String userUuid,
"/userprofile/{userId}"  <---  this was the path that has been mentioned in the Proejct

2020-12-05 18:39 UTC, jeffgtxjava commented on quora-api/src/main/java/com/upgrad/quora/api/controller/UserController.java
> +        userEntity.setSalt("abc1234");
done..!

2020-12-05 18:39 UTC, jeffgtxjava commented on quora-api/src/main/java/com/upgrad/quora/api/controller/UserController.java
> +        SignupUserResponse userResponse = new SignupUserResponse().id(createdUserEntity.getUuid()).status("REGISTERED");
done...!

2020-12-05 23:40 UTC, jeffgtxjava commented on quora-api/src/main/java/com/upgrad/quora/api/controller/AdminController.java
> +
done

2020-12-05 23:40 UTC, jeffgtxjava commented on quora-service/src/main/java/com/upgrad/quora/service/business/UserAdminBusinessService.java
> +        if(userAuthEntity.getLogoutAt() != null) {
I have updated the logic

2020-12-05 23:40 UTC, jeffgtxjava commented on quora-service/src/main/java/com/upgrad/quora/service/business/UserAdminBusinessService.java
> +        UserAuthEntity userAuthEntity1 = userDao.getUserAuthTokenByUuid(userUuid);
I did check that again and made changes  accordingly

2020-12-05 23:40 UTC, jeffgtxjava commented on quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java
> +        }catch (NoResultException nre) {
done
changed it to "Exception"

2020-12-05 23:40 UTC, jeffgtxjava commented on quora-api/src/main/java/com/upgrad/quora/api/controller/UserController.java
> +        signoutResponse.setMessage("SIGNED OUT SUCCESSFULLY");
done

2020-12-06 04:22 UTC, saharsa commented on quora-api/src/main/java/com/upgrad/quora/api/controller/CommonController.java
> +    public ResponseEntity<UserDetailsResponse> getUserDetailByUuid(@PathVariable("userId") final String userUuid,
For the method name. Path is correct.

2020-12-06 05:19 UTC, saharsa approved these changes
Please go ahead and merge

2020-12-06 13:29 UTC, merged